### PR TITLE
Updated articles.yml with 3 Remix Articles

### PR DESCRIPTION
**Pull request by cbenjamin2009**
Added 3 articles that I wrote from my blog regarding Remix. 
1. Article on creating a blog with MongoDB database, Prisma, and hosted on Vercel
2. Article on firebase authentication with Remix
3. Article showing how to fetch and render data and some TailwindCSS 3.0 styling

This is my first pull request on this repo, if I've done anything incorrect please let me know.

### CODE REVIEW

**Comment by cbenjamin2009** [comment]
Inclues 1 addition to Examples as well that includes an example of article 2 firebase authentication.

**Comment by edmundhung** [comment]
Hi @cbenjamin2009. Thanks for the PR. It looks like the first article link is not working. Can you check if the url is correct? For the example one, I would also suggest getting a repository link instead as that would help people figure out how you do it.

**Comment by cbenjamin2009** [comment]
Edmund, Thank you.. I've fixed the URL to include the full path to the article and it works now. I've also updated the example to point to my GitHub repo instead of the Vercel link.

**Comment by edmundhung** [comment]
Looks good! Thanks 👍🏼

**Pull request merged**
